module.exports = {
    en: {
        menu: {
            home: 'Home',
            submitclaim: "Submit Claim",
            ourworld: "Our World",
            aboutus:"About Us",
            missionandvisionactivities: "Mission and Vision Activities",
            memoranda: "Memoranda",
            branches: "Branches",
            masterclasses: "Masterclasses",
            academy:"Academy",
            longtermcourses:"Long-term Courses",
            shorttermcourses:"Short-term Courses",
            teachers:"Teachers",
            media:"Media",
            photogallery:"Photo Gallery",
            blog:"Blog",
            contact:"Contact",
            partners:"Partners",
            stateandprivatestructures:"State and private structures",
            scholarships:"Scholarships",
            costofcourses:"Cost of courses",
            beyondtheclassroom:"Beyond the classroom",
            ourstudentsandfamilies:"Our students and families",
            socialization:"Socialization",
            culturaltours:"Cultural tours",
            fromonlinecoursestorealliferelationships:"From online courses to real-life relationships",
            pressrelease:"Press release",
            videogallery:"Video gallery"
        }

    },
    ka: {
        menu: {
            home: 'მთავარი',
            submitclaim: "შეავსეთ განაცხადი",
            ourworld: "ჩვენი სამყარო",
            aboutus:"ჩვენს შესახებ",
            missionandvisionactivities:"მისია და ხედვა საქმიანობა",
            memoranda:"მემორანდუმები",
            branches: "ფილიალები",
            masterclasses:"მასტერკლასები (წარმატებული დიასპორელების)",
            academy:"აკადემია",
            longtermcourses:"გრძელვადიანი კურსები",
            shorttermcourses:"მოკლევადიანი კურსები",
            teachers:"პედაგოგები",
            media:"მედია",
            photogallery:"ფოტოგალერია",
            blog:"ბლოგი",
            contact:"კონტაქტი",
            partners:"პარტნიორები",
            stateandprivatestructures:"სახელმწიფო და კერძო სტრუქტურები",
            scholarships:"სტიპენდიები",
            costofcourses:"კურსების ღირებულება",
            beyondtheclassroom:"კლასსმიღმა",
            ourstudentsandfamilies:"ჩვენი სტუდენტები და ოჯახები",
            socialization:"სოციალიზაცია",
            culturaltours:"კულტურული ტურები",
            fromonlinecoursestorealliferelationships:"ონლაინ კურსებიდან რეალურ ურთიეთობამდე",
            pressrelease:"პრესრელიზი",
            videogallery:"ვიდეოგალერეა",
        }
    }
}